"""
Claim 2 (application A, REAL-DATA version) - GESPI conformal RISK CONTROL on REAL AlphaFold DB
predictions vs REAL experimental structures (Section 4.1's task, real protein instances).

This replaces the illustrative sigmoid-DGP of repro_claim2a.py with MEASURED (confidence, error)
pairs for real proteins: AlphaFold2 is NOT run here (out of CPU scope, per the paper); instead we
download AlphaFold DB's already-computed, public predicted structures (real pLDDT confidence,
DeepMind/EMBL-EBI, https://alphafold.ebi.ac.uk) for a curated panel of real UniProt proteins, and
the REAL experimental structures for the SAME proteins from the RCSB PDB (https://www.rcsb.org),
then compute a REAL per-residue error indicator: after a Kabsch (least-squares) superposition of
the predicted structure onto the real experimental structure (residues matched by pairwise sequence
alignment, so no reliance on matching residue numbering), e = 1 if the post-superposition CA-CA
distance > 3 Angstrom, else 0. This is exactly the error criterion used in the paper text and in
repro_claim2a.py's DGP ("err > 3 Angstrom"), now measured on real coordinates instead of simulated.

GESPI itself (Eq. 2, the min/max threshold construction) and conformal risk control (Angelopoulos
et al. 2024) are UNCHANGED from repro_claim2a.py - only the data source changes: real measured
(c, e) residue pairs instead of a sigmoid law.

Data sources (all public, no login, no GPU, downloaded fresh unless already cached locally under
real_data_cache/):
  - AlphaFold DB REST API + files: https://alphafold.ebi.ac.uk/api/prediction/{UniProt}
                                     -> pdbUrl (predicted structure with pLDDT in the B-factor column)
  - RCSB PDB:                       https://files.rcsb.org/download/{PDBID}.pdb  (real, experimental)

Curated real-protein panel (19 successfully processed; see PANEL below for exact UniProt/PDB/chain
IDs and provenance). 16 are well-characterized single-domain proteins that AlphaFold predicts with
near-zero real error (the "EASY" pool). 3 are real, substantially harder cases where AlphaFold's
predicted structure disagrees with the real experimental structure much more often despite still
being moderately-to-highly confident: the SARS-CoV-2 spike glycoprotein monomer prediction vs the
real cryo-EM trimer structure (6VXX), an isolated fibronectin FN-III module (1FNF) vs the
full-length multi-domain AF model, and the Ca2+-binding light chain of coagulation Factor X (1XKA)
vs its calcium-free AF model (the "HARD" pool).

The REAL analogue of repro_claim2a.py's "over-optimistic adversarial synthetic" regime is built from
these two real pools directly, with NO invented shift: a synthetic-augmentation set drawn only from
the EASY pool (well-characterized proteins that happen to be uniformly easy) looks safe in isolation,
but the TRUE real-world deployment distribution (the fixed test pool, bootstrapped from the full
mixed easy+hard panel) also contains real proteins like the ones in the HARD pool, where confidence
does not reliably track accuracy. Calibrating "OnlySynth"/"NaivePooled" only on the easy-only
synthetic sample and then deploying on the real mixed distribution is the honest, real-data analogue
of the paper's synthetic-data-quality hazard - obtained by choosing which REAL proteins go in the
synthetic-augmentation set, not by shifting a simulated law.

Because the curated real panel has only 19 proteins (4134 measured residues total) - far fewer
than the paper's N=1000 synthetic proteins - Monte-Carlo trials are generated by NONPARAMETRIC
BOOTSTRAP: resampling residues WITH REPLACEMENT from the fixed, real, measured (c, e) pool. Since
resampling with replacement from a finite population is exactly equivalent in distribution to i.i.d.
draws from that population's empirical law, this preserves the "T trials with an MC standard error"
structure of repro_claim2a.py while every draw is built exclusively from real measured values (no
invented probability law). All reported precision is therefore bounded by the real panel's finite
size - stated explicitly in the output.

Paper knobs matched: real proteins n=10 (used to size the real-calibration draw, Rr = n*M, M=50, as
in repro_claim2a.py), alpha in {5,10,15}%, eps=5%. "N=1000 synthetic proteins" is approximated by a
Rs=5000-residue bootstrap draw (matching repro_claim2a.py's Rs), since we do not have 1000 distinct
real synthetic proteins; this is a real limitation, stated explicitly below and in the logbook page.
"""
import os, sys, io, json, warnings, urllib.request
os.environ.setdefault("OMP_NUM_THREADS", "1"); os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")
warnings.filterwarnings("ignore")
import numpy as np
from pathlib import Path

HERE = Path(__file__).parent
CACHE_DIR = HERE / "real_data_cache"
CACHE_DIR.mkdir(exist_ok=True)
RESIDUE_CACHE = HERE / "real_protein_residues.json"

# ---------------------------------------------------------------------------
# Curated real-protein panel: (UniProt accession, PDB ID, chain, label, pool)
# pool: "easy" = well-characterized single-domain protein, near-zero real error.
#       "hard" = real, harder case with measurable pLDDT/error miscalibration.
# ---------------------------------------------------------------------------
PANEL = [
    ("P00698", "6LYZ", "A", "Lysozyme C (chicken)",                         "easy"),
    ("P0CG53", "1UBQ", "A", "Ubiquitin (bovine)",                           "easy"),
    ("P02185", "1A6N", "A", "Myoglobin (sperm whale)",                      "easy"),
    ("P61626", "1REX", "A", "Lysozyme C (human)",                           "easy"),
    ("P00918", "1CA2", "A", "Carbonic anhydrase 2 (human)",                 "easy"),
    ("P69905", "1SI4", "A", "Hemoglobin alpha (human)",                     "easy"),
    ("P68871", "1SI4", "B", "Hemoglobin beta (human)",                      "easy"),
    ("P01112", "5P21", "A", "HRAS (human)",                                 "easy"),
    ("P62942", "1FKB", "A", "FKBP1A (human)",                               "easy"),
    ("P00760", "1TRN", "A", "Trypsin (bovine)",                             "easy"),
    ("P02766", "1F41", "A", "Transthyretin (human)",                        "easy"),
    ("P01009", "1QLP", "A", "Alpha-1-antitrypsin (human)",                  "easy"),
    ("P00441", "2C9V", "A", "SOD1 (human)",                                 "easy"),
    ("P04406", "1U8F", "O", "GAPDH (human)",                                "easy"),
    ("P02753", "1RBP", "A", "Retinol binding protein (human)",              "easy"),
    ("P61769", "1A1M", "B", "Beta-2-microglobulin (human)",                 "easy"),
    ("P0DTC2", "6VXX", "A", "SARS-CoV-2 Spike glycoprotein (monomer pred. vs real trimer)", "hard"),
    ("P02751", "1FNF", "A", "Fibronectin FN-III module (human)",            "hard"),
    ("P00742", "1XKA", "L", "Coagulation Factor X light chain (human)",     "hard"),
]

AA3TO1 = {
 'ALA':'A','ARG':'R','ASN':'N','ASP':'D','CYS':'C','GLN':'Q','GLU':'E','GLY':'G',
 'HIS':'H','ILE':'I','LEU':'L','LYS':'K','MET':'M','PHE':'F','PRO':'P','SER':'S',
 'THR':'T','TRP':'W','TYR':'Y','VAL':'V','MSE':'M'}

def fetch(url, dest):
    if dest.exists():
        return dest.read_bytes()
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    data = urllib.request.urlopen(req, timeout=60).read()
    dest.write_bytes(data)
    return data

def af_pdb_url(uniprot):
    url = f"https://alphafold.ebi.ac.uk/api/prediction/{uniprot}"
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    data = json.load(urllib.request.urlopen(req, timeout=30))
    return data[0]["pdbUrl"]

def extract_chain(pdb_bytes, chain_id):
    from Bio.PDB import PDBParser
    parser = PDBParser(QUIET=True)
    struct = parser.get_structure("s", io.StringIO(pdb_bytes.decode("utf-8", errors="ignore")))
    model = next(iter(struct))
    chain = model[chain_id]
    seq, coords, bfac = [], [], []
    for res in chain:
        resname = res.get_resname()
        if resname not in AA3TO1 or "CA" not in res:
            continue
        seq.append(AA3TO1[resname])
        coords.append(res["CA"].get_coord())
        bfac.append(res["CA"].get_bfactor())
    return "".join(seq), np.array(coords, dtype=np.float64), np.array(bfac, dtype=np.float64)

def kabsch_error(mobile, fixed):
    mc = mobile - mobile.mean(axis=0); fc = fixed - fixed.mean(axis=0)
    U, S, Vt = np.linalg.svd(mc.T @ fc)
    d = np.sign(np.linalg.det(Vt.T @ U.T))
    R = Vt.T @ np.diag([1, 1, d]) @ U.T
    fit = (R @ mc.T).T + fixed.mean(axis=0)
    return np.linalg.norm(fit - fixed, axis=1)

def align_and_measure(uniprot, pdb_id, chain_id):
    from Bio.Align import PairwiseAligner, substitution_matrices
    af_url = af_pdb_url(uniprot)
    af_bytes = fetch(af_url, CACHE_DIR / f"AF-{uniprot}.pdb")
    exp_bytes = fetch(f"https://files.rcsb.org/download/{pdb_id}.pdb", CACHE_DIR / f"{pdb_id}.pdb")
    af_seq, af_coords, af_plddt = extract_chain(af_bytes, "A")
    exp_seq, exp_coords, _ = extract_chain(exp_bytes, chain_id)
    aligner = PairwiseAligner()
    aligner.mode = "global"
    aligner.substitution_matrix = substitution_matrices.load("BLOSUM62")
    aligner.open_gap_score = -10; aligner.extend_gap_score = -0.5
    aligner.target_end_gap_score = 0.0; aligner.query_end_gap_score = 0.0
    aln = aligner.align(af_seq, exp_seq)[0]
    tgt_blocks, qry_blocks = aln.aligned
    af_idx, exp_idx = [], []
    for (t0, t1), (q0, q1) in zip(tgt_blocks, qry_blocks):
        for k in range(t1 - t0):
            ti, qi = t0 + k, q0 + k
            if af_seq[ti] == exp_seq[qi]:
                af_idx.append(ti); exp_idx.append(qi)
    af_m, exp_m, plddt_m = af_coords[af_idx], exp_coords[exp_idx], af_plddt[af_idx]
    dist = kabsch_error(af_m, exp_m)
    return plddt_m / 100.0, (dist > 3.0).astype(np.float64), len(af_idx), af_url, pdb_id, chain_id

def build_real_dataset():
    if RESIDUE_CACHE.exists():
        cached = json.loads(RESIDUE_CACHE.read_text())
        return cached
    per_protein = []
    for uniprot, pdb_id, chain_id, label, pool in PANEL:
        c, e, n_match, af_url, _, _ = align_and_measure(uniprot, pdb_id, chain_id)
        per_protein.append(dict(uniprot=uniprot, pdb_id=pdb_id, chain=chain_id, label=label, pool=pool,
                                 n_match=n_match, af_url=af_url,
                                 rcsb_url=f"https://files.rcsb.org/download/{pdb_id}.pdb",
                                 c=c.tolist(), e=e.tolist(),
                                 mean_plddt=float(c.mean() * 100), error_rate=float(e.mean())))
        print(f"  fetched {label:50} {uniprot}/{pdb_id}:{chain_id}  n_match={n_match:4d} "
              f"mean_pLDDT={c.mean()*100:5.1f} real_error_rate={e.mean():.3f}")
    RESIDUE_CACHE.write_text(json.dumps(per_protein, indent=2))
    return per_protein

print("GESPI Claim 2A (REAL DATA) | conformal risk control on real AlphaFold DB pLDDT vs real PDB structures")
print("Downloading / loading cached real per-residue (confidence, error) data for the curated panel...")
data = build_real_dataset()

easy_c = np.concatenate([np.array(p["c"]) for p in data if p["pool"] == "easy"])
easy_e = np.concatenate([np.array(p["e"]) for p in data if p["pool"] == "easy"])
hard_c = np.concatenate([np.array(p["c"]) for p in data if p["pool"] == "hard"])
hard_e = np.concatenate([np.array(p["e"]) for p in data if p["pool"] == "hard"])
full_c = np.concatenate([easy_c, hard_c]); full_e = np.concatenate([easy_e, hard_e])
n_proteins = len(data)
print(f"\nReal panel: {n_proteins} proteins, {len(full_c)} matched residues "
      f"(easy pool {len(easy_c)} residues from {sum(1 for p in data if p['pool']=='easy')} proteins, "
      f"hard pool {len(hard_c)} residues from {sum(1 for p in data if p['pool']=='hard')} proteins)")
print(f"Overall real error rate (>3A after superposition): {full_e.mean():.4f}  "
      f"(easy pool {easy_e.mean():.4f}, hard pool {hard_e.mean():.4f})")

# ---- GESPI conformal risk control (Eq. 2), reused unchanged from repro_claim2a.py ----
n, alphas, eps = 10, [0.05, 0.10, 0.15], 0.05
M = 50; Rr = n * M            # real-calibration residues per trial (paper: n=10 proteins x M=50)
Rs = 5000                     # synthetic-calibration residues per trial (paper: N=1000 synth proteins)
Rtest = 20000                 # bootstrap test-pool size (bounded by the 4134 unique real residues)
T, SEED = 3000, 20260717
rng = np.random.default_rng(SEED)

def thresholds(c, e, n_examples, target_levels):
    Tn, R = c.shape
    order = np.argsort(-c, axis=1)
    c_sorted = np.take_along_axis(c, order, axis=1)
    e_sorted = np.take_along_axis(e, order, axis=1)
    Sk = np.cumsum(e_sorted, axis=1)
    out = {}
    for a in target_levels:
        t = a - (1.0 - a) / n_examples
        cap = t * R
        k = (Sk <= cap).sum(axis=1)
        lam = np.empty(Tn)
        abstain_all = k <= 0; accept_all = k >= R; mid = ~abstain_all & ~accept_all
        lam[abstain_all] = np.inf; lam[accept_all] = -np.inf
        idx = k[mid]
        lam[mid] = 0.5 * (c_sorted[mid, idx - 1] + c_sorted[mid, idx])
        out[round(a, 3)] = lam
    return out

def bootstrap_draw(pool_c, pool_e, rng, shape):
    idx = rng.integers(0, len(pool_c), size=shape)
    return pool_c[idx], pool_e[idx]

# fixed bootstrap test pool, drawn once from the REAL (mixed easy+hard) empirical distribution
test_idx = rng.integers(0, len(full_c), size=Rtest)
tc, te = full_c[test_idx], full_e[test_idx]
tc_sorted_order = np.argsort(tc); tc_sorted = tc[tc_sorted_order]; te_by_c = te[tc_sorted_order]
suffix_err = np.concatenate([np.cumsum(te_by_c[::-1])[::-1], [0.0]])

def eval_thr(lam):
    lam = np.asarray(lam, float)
    pos = np.searchsorted(tc_sorted, lam, side="left")
    risk = suffix_err[pos] / Rtest
    abstain = pos / Rtest
    risk = np.where(np.isposinf(lam), 0.0, risk); abstain = np.where(np.isposinf(lam), 1.0, abstain)
    risk = np.where(np.isneginf(lam), te.mean(), risk); abstain = np.where(np.isneginf(lam), 0.0, abstain)
    return risk, abstain

def mc(x): return float(x.mean()), float(x.std() / np.sqrt(len(x)))

results = {}
print(f"\nGESPI bootstrap params: n={n} (Rr={Rr} real residues/trial) Rs={Rs} Rtest={Rtest} T={T} "
      f"eps={eps} seed={SEED}")
for regime, synth_pool in [("informative_real", (full_c, full_e)), ("adversarial_real_easypool", (easy_c, easy_e))]:
    rc, re_ = bootstrap_draw(full_c, full_e, rng, (T, Rr))
    sc, se_ = bootstrap_draw(synth_pool[0], synth_pool[1], rng, (T, Rs))
    pc = np.concatenate([rc, sc], axis=1); pe = np.concatenate([re_, se_], axis=1)
    lev = sorted(set(alphas + [a + eps for a in alphas]))
    lam_real = thresholds(rc, re_, n, lev)
    lam_synth = thresholds(sc, se_, 1000, alphas)   # "N=1000 synthetic proteins" knob used in the level formula
    lam_pool = thresholds(pc, pe, n + 1000, alphas)
    print(f"\n== regime: {regime} (synthetic pool: "
          f"{'same real mixed easy+hard distribution as the test pool' if regime=='informative_real' else 'REAL easy-only proteins (over-optimistic vs the real mixed test pool, which also contains hard real proteins)'}) ==")
    print(f"{'alpha':>5} {'method':>11} {'risk':>7} {'+-SE':>6} {'<=a?':>5} {'<=a+e?':>6} {'abstain%':>8} {'+-SE':>5} {'absRedVsReal%':>13}")
    results[regime] = {}
    for a in alphas:
        la = lam_real[round(a, 3)]; lae = lam_real[round(a + eps, 3)]
        lp = lam_pool[round(a, 3)]; ls = lam_synth[round(a, 3)]
        lg = np.minimum(la, np.maximum(lp, lae))
        r_or, ab_or = eval_thr(la)
        row = {}
        for name, lam in [("OnlyReal", la), ("OnlySynth", ls), ("NaivePooled", lp), ("GESPI", lg)]:
            risk, ab = eval_thr(lam)
            mrisk, mrisk_se = mc(risk); mab, mab_se = mc(ab * 100)
            dred = (ab_or - ab); mdred, sdred = mc(dred * 100)
            redpct = float((1 - ab.mean() / max(ab_or.mean(), 1e-12)) * 100)
            row[name] = dict(risk=mrisk, risk_se=mrisk_se, abstain_pct=mab, abstain_se=mab_se,
                              valid_le_alpha=bool(mrisk <= a + 3e-3),
                              guard_le_alpha_eps=bool(mrisk <= a + eps + 3e-3),
                              abstain_reduction_vs_onlyreal_pct=redpct,
                              abstain_reduction_pp=mdred, abstain_reduction_pp_se=sdred)
            tag_red = f"{redpct:6.1f} ({mdred/max(sdred,1e-9):4.0f}SE)" if name == "GESPI" else f"{redpct:6.1f}"
            print(f"{a:5.2f} {name:>11} {mrisk:7.4f} {mrisk_se:6.4f} {str(mrisk<=a+3e-3):>5} "
                  f"{str(mrisk<=a+eps+3e-3):>6} {mab:8.1f} {mab_se:5.2f} {tag_red:>13}")
        results[regime][f"{a:.2f}"] = row

print("\n--- Checks (pre-registered, mirroring repro_claim2a.py) ---")
inf = results["informative_real"]; adv = results["adversarial_real_easypool"]
onlyreal_valid = all(inf[f"{a:.2f}"]["OnlyReal"]["valid_le_alpha"] for a in alphas)
gespi_valid_inf = all(inf[f"{a:.2f}"]["GESPI"]["valid_le_alpha"] for a in alphas)
gespi_guard_adv = all(adv[f"{a:.2f}"]["GESPI"]["guard_le_alpha_eps"] for a in alphas)
eff_sep = all(inf[f"{a:.2f}"]["GESPI"]["abstain_reduction_pp"] >
              5 * max(inf[f"{a:.2f}"]["GESPI"]["abstain_reduction_pp_se"], 1e-9) for a in alphas)
red = [round(inf[f"{a:.2f}"]["GESPI"]["abstain_reduction_vs_onlyreal_pct"], 1) for a in alphas]
naive_pool_breaks = any(adv[f"{a:.2f}"]["NaivePooled"]["risk"] > a + 0.01 for a in alphas)
only_synth_breaks = any(adv[f"{a:.2f}"]["OnlySynth"]["risk"] > a + 0.01 for a in alphas)
print(f"[validity] OnlyReal risk <= alpha (informative_real): {onlyreal_valid}")
print(f"[validity] GESPI risk <= alpha (informative_real): {gespi_valid_inf}")
print(f"[validity] GESPI risk <= alpha+eps guardrail (adversarial_real_easypool): {gespi_guard_adv}")
print(f"[efficiency] GESPI abstains LESS than OnlyReal at every alpha (>5 SE), reductions%={red}: {eff_sep}")
print(f"[control] NaivePooled VIOLATES risk (> alpha) under real easy-only (over-optimistic) synthetic pool: {naive_pool_breaks}")
print(f"[control] OnlySynth VIOLATES risk (> alpha) under real easy-only (over-optimistic) synthetic pool: {only_synth_breaks}")
PASS = bool(onlyreal_valid and gespi_valid_inf and gespi_guard_adv and eff_sep)
print(f"\nVERDICT PASS = {PASS}")
print(f"\n[LIMITATION] Real curated panel = {n_proteins} proteins / {len(full_c)} measured residues total "
      f"(vs paper's n=10 real + N=1000 synthetic proteins). Monte-Carlo trials are a nonparametric "
      f"bootstrap over this fixed real (confidence, error) empirical distribution, not a resample from "
      f"an infinite population; precision is bounded by this real sample size.")

out = dict(experiment="claim2a_conformal_risk_control_REAL_DATA",
           paper="arXiv 2509.20345 GESPI Sec 4.1",
           data_sources=dict(
               alphafold_db="https://alphafold.ebi.ac.uk (AlphaFold DB REST API + files, real pLDDT)",
               rcsb_pdb="https://files.rcsb.org (real experimental structures)",
           ),
           panel=[dict(uniprot=p["uniprot"], pdb_id=p["pdb_id"], chain=p["chain"], label=p["label"],
                       pool=p["pool"], n_match=p["n_match"], mean_plddt=p["mean_plddt"],
                       error_rate=p["error_rate"], af_url=p["af_url"], rcsb_url=p["rcsb_url"])
                  for p in data],
           n_proteins=n_proteins, n_residues_total=int(len(full_c)),
           n_residues_easy=int(len(easy_c)), n_residues_hard=int(len(hard_c)),
           n=n, alphas=alphas, eps=eps, M=M, Rr=Rr, Rs=Rs, Rtest=Rtest, T=T, seed=SEED,
           results=results,
           checks=dict(onlyreal_valid=bool(onlyreal_valid), gespi_valid_informative=bool(gespi_valid_inf),
                       gespi_guardrail_adversarial=bool(gespi_guard_adv), efficiency_separated=bool(eff_sep),
                       abstain_reductions_pct=red, naive_pooled_breaks_adv=bool(naive_pool_breaks),
                       only_synth_breaks_adv=bool(only_synth_breaks), PASS=PASS))
Path(__file__).with_name("results_2a_real.json").write_text(json.dumps(out, indent=2))
print("wrote results_2a_real.json")
